# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.1
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8008
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 静态证书路径存储
ocspConfiguration:
  CAPath: /opt/apache-tomcat-9.0.56/webapps/cert/rootCA-digicert.pem
  keyPath: /opt/apache-tomcat-9.0.56/webapps/cert/key.pem
  CRLPath: /opt/apache-tomcat-9.0.56/webapps/cert/AllCRL.crl
#  CAPath: ruoyi-system\\src\\main\\resources\\cert\\rootCA-digicert.pem
#  keyPath: ruoyi-system\\src\\main\\resources\\cert\\key.pem
#  CRLPath: ruoyi-system\\src\\main\\resources\\cert\\AllCRL.crl
  synUrl: http://192.168.8.202:4130/cipher/public/
  crlUrl: http://192.168.8.169/cipher/public/revokelist/AllCRL.crl

CRLConfiguratin:
  crlIP: 192.168.8.169
  crlROOT: root
  crlPASSWORD: 197154
  crlPORT: 222

CAConfig:
  CAPrivate: /opt/apache-tomcat-9.0.56/webapps/rootca/Root.key
  CAPath: /opt/apache-tomcat-9.0.56/webapps/rootca/RootCA.crt
#  CAPrivate: ruoyi-system/src/main/resources/rootca/Root.key
#  CAPath: ruoyi-system/src/main/resources/rootca/RootCA.crt

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.8.170
    # 端口，默认为6379
    port: 6381
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30

# MyBatis配置
#mybatis:
#    # 搜索指定包别名
#    typeAliasesPackage: com.ruoyi.**.domain
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mapper/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ruoyi.**.domain
  config-location: classpath:mybatis/mybatis-config.xml



# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
